# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    menus_directory: '%kernel.project_dir%/public/uploads/menus'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\NoSql\AllergeneService:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'
